version: '3'
services:
  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
  web:
    image: zero1zero/vestly-web:${TAG}
    ports:
      - "5000:5000"
  api:
    image: zero1zero/vestly-api:${TAG}
    ports:
      - "8080:8080"
