apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      containers:
        - image: '990223444407.dkr.ecr.us-west-2.amazonaws.com/bingematch-api:latest'
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector: 
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
