apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |

    events {}

    http {
      server {
        server_name nginx;

        location /api/ {
          proxy_pass http://api.default.svc.cluster.local:8080/;
          #rewrite ^(.*)$ $1 break;
        }

        location / {
          proxy_pass http://ui.default.svc.cluster.local:5000/;
          #rewrite ^/web(.*)$ $1 break;i
        }
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
